"""add embedding column to ads

Revision ID: f3cd2b078a00
Revises: 55fc6f246fe5
Create Date: 2025-11-21 15:56:49.776362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3cd2b078a00'
down_revision: Union[str, Sequence[str], None] = '55fc6f246fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('embedding', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'embedding')
    # ### end Alembic commands ###
